#!/usr/bin/env python

import cgitb
cgitb.enable()

# Print necessary headers.
print("Content-Type: text/html")
print()

# Connect to the database.
import pymysql
conn = pymysql.connect(
user='admin',
passwd='password',
host='mysqldb.cwcqnl6kkz7p.ap-south-1.rds.amazonaws.com')
c = conn.cursor()

# Create table and Insert some example data.
c.execute("CREATE DATABASE IF NOT EXISTS mysqldb")
c.execute("USE mysqldb")
try:
    c.execute("CREATE TABLE numbers (num INT, word VARCHAR(20))")
except:
    print("")
c.execute("INSERT INTO numbers VALUES (1, 'One!')")
c.execute("INSERT INTO numbers VALUES (2, 'Two!')")
c.execute("INSERT INTO numbers VALUES (3, 'Three!')")
conn.commit()

# Print the contents of the database.
c.execute("SELECT * FROM numbers")

print([(r[0], r[1]) for r in c.fetchall()])

